name: Build Grasshopper Plugin

on:
  push:
    branches: [develop]
    paths-ignore:
      - "website/**"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "website/**"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest # For a list of available runner types, refer to

    env:
      Solution_Name: HoaryFox.sln
      Plugin_File_Name: HoaryFox

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Build the application
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Copy Samples & License to /HoaryFox/bin dir
        if: ${{ matrix.configuration == 'Release' }} # Only upload gha from a release build
        shell: powershell
        run: |
          cp ./Samples ./Release/Samples -recurse
          cp ./LICENSE ./Release/LICENSE

      - name: Upload release build of plugin as artefact
        if: ${{ matrix.configuration == 'Release' }} # Only upload gha from a release build
        uses: actions/upload-artifact@v2
        with:
          name: HoaryFox
          path: |
            ./Release
