name: test build document site

on:
  pull_request:
    branches: [develop]
    paths:
      - "website/**"

jobs:
  test-build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: website

    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn build

  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Create comments
      run: |
        echo "アップデートに向けて以下更新したか？" >> comments
        echo "- package.json のバージョン" >> comments
        sed -i -z 's/\n/\\n/g' comments
    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -d "{\"body\": \"$(cat comments)\"}" \
            ${URL}